### PR TITLE
solved bug find accomplices, added test

### PR DESCRIPTION
**Pull request by Kubasinska**
1. Solved bug in find accomplices #28 
2. Added test

### CODE REVIEW

**Review by mariopaolucci — CHANGES_REQUESTED** [review]
Why are we
- doing two things in the same commit
- adding the test in the main release when there's no test routine for it?
I suggest removing the test altogether from here. Let's keep it in a test branch until it's ready to be automatized. Also, I really do not want names like test2 in the main branch..

**Comment by Kubasinska** [comment]
@mariopaolucci  updated!

**Review by mariopaolucci — APPROVED** [review]
C'è sempre test/__init__.py  ma ok

**Comment by Kubasinska** [comment]
Impossible, the entire test folder has been deleted!

**Pull request merged**
